### ISSUE TITLE
I2C not reporting on Esphome?

### ISSUE THREAD

**Issue by benhoff** [gcormier/esphome-pressure#4]
Hey I have the following for the yaml with esphome:

``` yaml
i2c:
  sda: 6
  scl: 7
  scan: true
  id: bus_a


sensor:
  - platform: xgzp68xx
    temperature:
      name: "Pressure Temperature"
    pressure:
      name: "Pressure Diff pressure"
    update_interval: 5s
```

However, I'm not seeing the DP sensor in esphome/home assistant. 
Are the pinout assignments on here correct or anything else I should look into?
